### PR TITLE
[libvirt] Do not use upstream /etc/conf.d files

### PR DESCRIPTION
**Pull request by kempniu**
Upstream `libvirt` package installs the following files:

  * `/etc/conf.d/libvirt-guests`
  * `/etc/conf.d/libvirtd`

The `libvirt-openrc` package in Artix also installs these files, albeit with different contents (taken from Gentoo).  This causes a conflict between these two packages:

```sh
# pacman -Ql | grep conf.d/libvirt
libvirt /etc/conf.d/libvirt-guests
libvirt /etc/conf.d/libvirtd
libvirt-openrc /etc/conf.d/libvirt-guests
libvirt-openrc /etc/conf.d/libvirtd
```

This PR attempts to resolve the issue by removing the offending files from the upstream `libvirt` package since the variables they contain are not used by the OpenRC init script anyway.

### CODE REVIEW

**Comment by udeved** [comment]
Hello, thanks for the PR, but our github is only a mirror, ie we don't do PRs on the mirror.
Will be fixed asap @alium

**Comment by kempniu** [comment]
So, before creating this PR, I asked on the `#artix` IRC channel how should package tweak suggestions be submitted (as I was unable to find clear directions on that subject on the Artix website) and I was told that:

> since gitea is read-only, github should be fine (if it's about packages)

Thus, here I am, though I will be happy to submit tweaks using some other channel you suggest.  Thanks!

**Comment by kempniu** [comment]
I am aware of all that but you have not really answered my implied question :)  Since I cannot register with Gitea, creating PRs on the GitHub mirror is not the way to do things, and - AFAICT - the Artix website does not specify how to submit PKGBUILD tweaks, then what is the preferred way of doing that?  I mean, I can probably send emails to the Artix maintainer(s) of each PKGBUILD but IMHO it would be beneficial to the community do this publicly.

**Comment by udeved** [comment]
In order to contribute at the moment, you would have to get in touch with us and we make you an gitea account, but only if you plan to regularly contribute. We are sparse with server resources.

**Comment by kempniu** [comment]
Okay, I do not want to burden you with creating an account at this time since I only have a few tweaks to suggest for now.  I guess I will use email after all, thanks.

**Comment by alium** [comment]
i updated libvirt's PKGBUILD as proposed https://github.com/artix-linux/packages-galaxy/pull/9/commits/7b399ccd9de68cdad4e1d14b330a3a34146bccb1

**Pull request closed without merging**
